#!/bin/bash

if [ -z $1 ] || [ -z $2 ]; then
  echo "USAGE: $0 <PUPPET_VERSION> <FQDN>"
fi

test -f Gemfile && (diff -Naur Gemfile.$1 Gemfile > /dev/null)
if [ $? -gt 0 ]; then
  [ -f Gemfile.lock ] && rm Gemfile.lock
  cp Gemfile.$1 Gemfile
fi
test -f Gemfile.lock ||  bundle > /dev/null

ETCDIR=$(readlink -f `dirname $0`)
PUPPETDIR=$(readlink -f `dirname $0`/../puppet)
CATALOG_DIR=$(readlink -f `dirname $0`/puppet_catalogs_$1)

test -d $CATALOG_DIR || mkdir $CATALOG_DIR

OUTPUT_FILE=$CATALOG_DIR/$2.out
CATALOG_FILE=$CATALOG_DIR/$2.pson
TIME_FILE=$CATALOG_DIR/$2.time
WARNINGS_FILE=$CATALOG_DIR/$2.warnings

if [ "$1" == "3" ]; then
  COMPILE_OPTIONS=""
else
  COMPILE_OPTIONS="--factsync true"
fi


bundle exec puppet master \
  --modulepath=$PUPPETDIR/modules/public:$PUPPETDIR/modules/site \
  --manifestdir $PUPPETDIR/manifests \
  --yamldir $ETCDIR/var/yaml \
  --confdir $ETCDIR/etc \
  --vardir $ETCDIR/var \
  --storeconfigs true \
  --masterlog $CATALOG_DIR/master.log \
  --thin_storeconfigs true \
  --pluginsync true $COMPILE_OPTIONS\
  --trace \
  --color false \
  --compile $2 > $OUTPUT_FILE

grep -E '^(.*0;36m)?notice: Compiled catalog for ' $OUTPUT_FILE | head -n 1 | sed 's/.*in \(.*\) seconds.*/\1/' > $TIME_FILE
grep -E '^(.*0;33m)?warning:' $OUTPUT_FILE > $WARNINGS_FILE
grep -vE '^(.*0;33m)?(notice|warning):' $OUTPUT_FILE > $CATALOG_FILE
